kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /dags/
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadOnlyMany
  resources:
   requests:
    storage: 2Gi